# Generated by Django 4.2.4 on 2023-08-07 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=110, verbose_name='Nombre Empresa')),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=11, verbose_name='su telefono')),
                ('pagina_web', models.URLField(verbose_name='Direccion pagina web')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre reunion')),
                ('fecha_reunion', models.DateTimeField(verbose_name='Fecha')),
                ('presentador', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('asistentes', models.ManyToManyField(blank=True, to='appreuniones.usuarioreunion')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appreuniones.empresa')),
            ],
        ),
    ]
